### ISSUE TITLE
[Feature] Setting for disable mixing hash

### ISSUE THREAD

**Issue by xion87** [vik1395/BungeeAuth-Minecraft#13]
A config that you can disable random hasha and keep the favourite password hash would be great.

**Comment by MaksymSemenykhin** [comment]
@xion87 even better:

```
Encrpytion:
        #Should Bungeeauth use a defined hash instead be random selected?
        Definedhash: true
        #If the above setting is true, specific the hash to use. (Supported hash MD5, SHA1, SHA256, SHA512... i dont remember other ones)
        HashtoUse: MD5

```
